// Package api: 客户端配置生成器（PRD §9.5）。
//
// 生成器按 client 来源 URL（X-Forwarded-Proto / r.TLS / r.Host 推断），
// 把每个 registry upstream 转成对应客户端格式：
//   - Docker Engine daemon.json
//   - containerd hosts.toml（每个上游一个文件）
//   - k3s / rke2 registries.yaml
//   - SteamCMD（Phase 2）
package api

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/cncachehub/server/internal/storage"
)

// timeNowUnix is a swappable clock for tests.
var timeNowUnix = func() int64 { return time.Now().Unix() }

// clientBaseURL 推断客户端访问 CNCacheHub 的 base URL。
//
// 优先级：X-Forwarded-Proto + X-Forwarded-Host > r.TLS + r.Host > r.Host (http)
func clientBaseURL(r *http.Request) string {
	scheme := "http"
	host := r.Host
	if v := r.Header.Get("X-Forwarded-Proto"); v != "" {
		scheme = v
	} else if r.TLS != nil {
		scheme = "https"
	}
	if v := r.Header.Get("X-Forwarded-Host"); v != "" {
		host = v
	}
	return scheme + "://" + host
}

// registryHostnameFromUpstream 把 upstream name 转成 client 端 registry 主机名。
//
// dockerhub → docker.io, ghcr → ghcr.io, k8s → registry.k8s.io, quay → quay.io
func registryHostnameFromUpstream(name string) string {
	switch name {
	case "dockerhub":
		return "docker.io"
	case "ghcr":
		return "ghcr.io"
	case "quay":
		return "quay.io"
	case "k8s":
		return "registry.k8s.io"
	default:
		return name + ".io"
	}
}

// clientConfigContext 客户端配置生成上下文。
type clientConfigContext struct {
	BaseURL     string
	Registry    storage.Registry
	RegistryURL string // client 端访问 CNCH 的该 registry URL（带 mirror_path）
	Hostname    string // 客户端面向的 registry 主机名
}

// clientConfigContextFromReq 从 request + DB registry 构造上下文。
func clientConfigContextFromReq(r *http.Request, reg storage.Registry) clientConfigContext {
	base := clientBaseURL(r)
	mirrorPath := reg.MirrorPath
	if mirrorPath == "" {
		mirrorPath = "/v2"
	}
	return clientConfigContext{
		BaseURL:     base,
		Registry:    reg,
		RegistryURL: base + mirrorPath,
		Hostname:    registryHostnameFromUpstream(reg.Name),
	}
}

// generateContainerdHostsTOML 生成 containerd hosts.toml（PRD §9.5.2）。
//
// 路径：/etc/containerd/certs.d/<registry-hostname>/hosts.toml
// 或 k3s 风格：放在 /etc/rancher/k3s/ 下的等价位置。
//
// 格式示例：
//
//   server = "https://ghcr.io"
//   [host."http://117.55.237.250"]
//     capabilities = ["pull", "resolve"]
//     skip_verify = true
func generateContainerdHostsTOML(c clientConfigContext) string {
	// 是否 https：base URL scheme 决定 host 项
	scheme := "http"
	if strings.HasPrefix(c.BaseURL, "https://") {
		scheme = "https"
	}
	return fmt.Sprintf(`# containerd hosts.toml — generated by CNCacheHub
# 目标路径：/etc/containerd/certs.d/%[1]s/hosts.toml
# 适用：containerd / nerdctl / k3s / rke2 / K8s containerd runtime
#
# 安装步骤：
#   1. 把本文件写入到目标路径
#   2. systemctl restart containerd  (或 k3s: systemctl restart k3s)
#   3. 验证：crictl pull %[1]s/library/nginx:latest
#         nerdctl pull %[1]s/library/nginx:latest
#
# k3s / rke2 路径不同：/etc/rancher/k3s/registries.yaml
#   用本接口的 k3s 模式生成。
server = "https://%[1]s"

[host."%[2]s"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
  override_path = true
`, c.Hostname, scheme+"://"+c.BaseURL[strings.Index(c.BaseURL, "://")+3:])
}

// generateK3sRegistriesYAML 生成 k3s / rke2 registries.yaml。
//
// 路径：/etc/rancher/k3s/registries.yaml
//
// 格式示例：
//
//   mirrors:
//     docker.io:
//       endpoint:
//         - "http://117.55.237.250"
//     ghcr.io:
//       endpoint:
//         - "http://117.55.237.250"
func generateK3sRegistriesYAML(c clientConfigContext) string {
	endpoint := strings.TrimSuffix(c.BaseURL, "/")
	return fmt.Sprintf(`# k3s / rke2 registries.yaml — generated by CNCacheHub
# 目标路径：/etc/rancher/k3s/registries.yaml
# 适用：k3s / rke2 / K8s containerd
#
# 安装步骤：
#   1. 把本文件写入 /etc/rancher/k3s/registries.yaml
#   2. systemctl restart k3s
#   3. 验证：crictl pull ghcr.io/jetstack/cert-manager-controller:v1.14.4
#
# 多 endpoint：列表加更多 mirror URL。
mirrors:
  %[1]s:
    endpoint:
      - "%[2]s"
`, c.Hostname, endpoint)
}

// clientConfigResponse 是 POST /api/client-config/* 响应。
type clientConfigResponse struct {
	Registry     string `json:"registry"`     // "dockerhub" / "ghcr" / ...
	Hostname     string `json:"hostname"`     // "docker.io" / "ghcr.io" / ...
	Format       string `json:"format"`       // "containerd-hosts" / "k3s-registries"
	Content      string `json:"content"`      // 配置文件内容
	TargetPath   string `json:"targetPath"`   // 安装目标路径
	RestartCmd   string `json:"restartCmd"`   // 重启命令
	VerifyCmd    string `json:"verifyCmd"`    // 验证命令
	GeneratedAt  int64  `json:"generatedAt"`
	CNCHBaseURL  string `json:"cnchBaseUrl"`  // CNCH base URL 用于回访
}

// clientConfigRequest 是 POST /api/client-config/* body。
type clientConfigRequest struct {
	Registry string `json:"registry"` // "dockerhub" / "ghcr" / "quay" / "k8s"
}

// generateClientConfigHandler POST /api/client-config/{format}?registry=...
//
// format: "containerd-hosts" 或 "k3s-registries"。
func generateClientConfigHandler(opts Options) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if opts.GetSettings == nil || opts.ListRegistries == nil {
			writeError(w, http.StatusServiceUnavailable, "client_config_unavailable", "registries not configured")
			return
		}
		format := r.URL.Query().Get("format")
		if format == "" {
			writeError(w, http.StatusBadRequest, "missing_format", "format query param required (containerd-hosts | k3s-registries)")
			return
		}
		registryName := r.URL.Query().Get("registry")
		if registryName == "" {
			writeError(w, http.StatusBadRequest, "missing_registry", "registry query param required")
			return
		}
		// 找上游
		regs, err := opts.ListRegistries(r.Context())
		if err != nil {
			writeError(w, http.StatusInternalServerError, "registries_query_failed", err.Error())
			return
		}
		var reg *Registry
		for i := range regs {
			if regs[i].Name == registryName {
				reg = &regs[i]
				break
			}
		}
		if reg == nil {
			writeError(w, http.StatusNotFound, "registry_not_found", "registry "+registryName+" not found")
			return
		}
		if !reg.Enabled {
			writeError(w, http.StatusBadRequest, "registry_disabled", "registry "+registryName+" is disabled")
			return
		}
		ctx := clientConfigContextFromReq(r, storage.Registry{
			ID:          reg.ID,
			Name:        reg.Name,
			UpstreamURL: reg.UpstreamURL,
			MirrorPath:  reg.MirrorPath,
			Enabled:     reg.Enabled,
			CreatedAt:   reg.CreatedAt,
		})

		now := nowUnix()
		resp := clientConfigResponse{
			Registry:    reg.Name,
			Hostname:    ctx.Hostname,
			Format:      format,
			CNCHBaseURL: ctx.BaseURL,
			GeneratedAt: now,
		}

		switch format {
		case "containerd-hosts":
			resp.Content = generateContainerdHostsTOML(ctx)
			resp.TargetPath = fmt.Sprintf("/etc/containerd/certs.d/%s/hosts.toml", ctx.Hostname)
			resp.RestartCmd = "systemctl restart containerd"
			resp.VerifyCmd = fmt.Sprintf("crictl pull %s/library/nginx:latest", ctx.Hostname)
		case "k3s-registries":
			resp.Content = generateK3sRegistriesYAML(ctx)
			resp.TargetPath = "/etc/rancher/k3s/registries.yaml"
			resp.RestartCmd = "systemctl restart k3s"
			resp.VerifyCmd = "crictl pull ghcr.io/jetstack/cert-manager-controller:v1.14.4"
		default:
			writeError(w, http.StatusBadRequest, "unsupported_format",
				"format must be containerd-hosts or k3s-registries")
			return
		}

		writeJSON(w, http.StatusOK, resp)
	}
}

// nowUnix 现在时间（unix 秒）。独立函数方便测试 mock。
func nowUnix() int64 {
	return timeNowUnix()
}
