// Package api: 客户端配置生成器（PRD §9.5）。
//
// 生成器按 client 来源 URL（X-Forwarded-Proto / r.TLS / r.Host 推断），
// 把每个 registry upstream 转成对应客户端格式：
//   - Docker Engine daemon.json
//   - containerd hosts.toml（每个上游一个文件）
//   - k3s / rke2 registries.yaml
//   - SteamCMD（Phase 2）
//
// §9.5.4 还提供一键 zip 配置包导出（POST /api/client-config/bundle）：
// 包含 daemon.json / containerd hosts / k3s registries / steamcmd docker-compose
// / resource-accelerators (playwright / puppeteer / terraformrc / helm-repos.sh)
// / verify.sh / README.md。
package api

import (
	"archive/zip"
	"bytes"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/cncachehub/server/internal/storage"
)

// timeNowUnix is a swappable clock for tests.
var timeNowUnix = func() int64 { return time.Now().Unix() }

// clientBaseURL 推断客户端访问 CNCacheHub 的 base URL。
//
// 优先级：opts.PublicBaseURL（admin 在 SettingsView 配的）> r.Host 推断。
//
// 为什么不直接用 r.Host：nginx 默认 proxy_set_header Host $proxy_host
// 让后端 r.Host 永远是 127.0.0.1:8082 而不是用户访问的公网 IP。
// 所以让 admin 显式配一次最稳；如果没配，fallback 到 r.Host（直连 8082 场景）。
func clientBaseURL(opts Options, r *http.Request) string {
	if opts.PublicBaseURL != "" {
		return opts.PublicBaseURL
	}
	scheme := "http"
	host := r.Host
	if v := r.Header.Get("X-Forwarded-Proto"); v != "" {
		scheme = v
	} else if r.TLS != nil {
		scheme = "https"
	}
	if v := r.Header.Get("X-Forwarded-Host"); v != "" {
		host = v
	}
	return scheme + "://" + host
}

// registryHostnameFromUpstream 把 upstream name 转成 client 端 registry 主机名。
//
// dockerhub → docker.io, ghcr → ghcr.io, k8s → registry.k8s.io, quay → quay.io
func registryHostnameFromUpstream(name string) string {
	switch name {
	case "dockerhub":
		return "docker.io"
	case "ghcr":
		return "ghcr.io"
	case "quay":
		return "quay.io"
	case "k8s":
		return "registry.k8s.io"
	default:
		return name + ".io"
	}
}

// clientConfigContext 客户端配置生成上下文。
type clientConfigContext struct {
	BaseURL     string
	Registry    storage.Registry
	RegistryURL string // client 端访问 CNCH 的该 registry URL（带 mirror_path）
	Hostname    string // 客户端面向的 registry 主机名
}

// clientConfigContextFromReq 从 request + DB registry 构造上下文。
func clientConfigContextFromReq(opts Options, r *http.Request, reg storage.Registry) clientConfigContext {
	base := clientBaseURL(opts, r)
	mirrorPath := reg.MirrorPath
	if mirrorPath == "" {
		mirrorPath = "/v2"
	}
	return clientConfigContext{
		BaseURL:     base,
		Registry:    reg,
		RegistryURL: base + mirrorPath,
		Hostname:    registryHostnameFromUpstream(reg.Name),
	}
}

// generateContainerdHostsTOML 生成 containerd hosts.toml（PRD §9.5.2）。
//
// 路径：/etc/containerd/certs.d/<registry-hostname>/hosts.toml
// 或 k3s 风格：放在 /etc/rancher/k3s/ 下的等价位置。
//
// 格式示例：
//
//   server = "https://ghcr.io"
//   [host."http://117.55.237.250"]
//     capabilities = ["pull", "resolve"]
//     skip_verify = true
func generateContainerdHostsTOML(c clientConfigContext) string {
	// 是否 https：base URL scheme 决定 host 项
	scheme := "http"
	if strings.HasPrefix(c.BaseURL, "https://") {
		scheme = "https"
	}
	return fmt.Sprintf(`# containerd hosts.toml — generated by CNCacheHub
# 目标路径：/etc/containerd/certs.d/%[1]s/hosts.toml
# 适用：containerd / nerdctl / k3s / rke2 / K8s containerd runtime
#
# 安装步骤：
#   1. 把本文件写入到目标路径
#   2. systemctl restart containerd  (或 k3s: systemctl restart k3s)
#   3. 验证：crictl pull %[1]s/library/nginx:latest
#         nerdctl pull %[1]s/library/nginx:latest
#
# k3s / rke2 路径不同：/etc/rancher/k3s/registries.yaml
#   用本接口的 k3s 模式生成。
server = "https://%[1]s"

[host."%[2]s"]
  capabilities = ["pull", "resolve"]
  skip_verify = true
  override_path = true
`, c.Hostname, scheme+"://"+c.BaseURL[strings.Index(c.BaseURL, "://")+3:])
}

// generateK3sRegistriesYAML 生成 k3s / rke2 registries.yaml。
//
// 路径：/etc/rancher/k3s/registries.yaml
//
// 格式示例：
//
//   mirrors:
//     docker.io:
//       endpoint:
//         - "http://117.55.237.250"
//     ghcr.io:
//       endpoint:
//         - "http://117.55.237.250"
func generateK3sRegistriesYAML(c clientConfigContext) string {
	endpoint := strings.TrimSuffix(c.BaseURL, "/")
	return fmt.Sprintf(`# k3s / rke2 registries.yaml — generated by CNCacheHub
# 目标路径：/etc/rancher/k3s/registries.yaml
# 适用：k3s / rke2 / K8s containerd
#
# 安装步骤：
#   1. 把本文件写入 /etc/rancher/k3s/registries.yaml
#   2. systemctl restart k3s
#   3. 验证：crictl pull ghcr.io/jetstack/cert-manager-controller:v1.14.4
#
# 多 endpoint：列表加更多 mirror URL。
mirrors:
  %[1]s:
    endpoint:
      - "%[2]s"
`, c.Hostname, endpoint)
}

// clientConfigResponse 是 POST /api/client-config/* 响应。
type clientConfigResponse struct {
	Registry     string `json:"registry"`     // "dockerhub" / "ghcr" / ...
	Hostname     string `json:"hostname"`     // "docker.io" / "ghcr.io" / ...
	Format       string `json:"format"`       // "containerd-hosts" / "k3s-registries"
	Content      string `json:"content"`      // 配置文件内容
	TargetPath   string `json:"targetPath"`   // 安装目标路径
	RestartCmd   string `json:"restartCmd"`   // 重启命令
	VerifyCmd    string `json:"verifyCmd"`    // 验证命令
	GeneratedAt  int64  `json:"generatedAt"`
	CNCHBaseURL  string `json:"cnchBaseUrl"`  // CNCH base URL 用于回访
}

// clientConfigRequest 是 POST /api/client-config/* body。
type clientConfigRequest struct {
	Registry string `json:"registry"` // "dockerhub" / "ghcr" / "quay" / "k8s"
}

// generateClientConfigHandler POST /api/client-config/{format}?registry=...
//
// format: "containerd-hosts" 或 "k3s-registries"。
func generateClientConfigHandler(opts Options) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if opts.GetSettings == nil || opts.ListRegistries == nil {
			writeError(w, http.StatusServiceUnavailable, "client_config_unavailable", "registries not configured")
			return
		}
		format := r.URL.Query().Get("format")
		if format == "" {
			writeError(w, http.StatusBadRequest, "missing_format", "format query param required (containerd-hosts | k3s-registries)")
			return
		}
		registryName := r.URL.Query().Get("registry")
		if registryName == "" {
			writeError(w, http.StatusBadRequest, "missing_registry", "registry query param required")
			return
		}
		// 找上游
		regs, err := opts.ListRegistries(r.Context())
		if err != nil {
			writeInternalErr(w, r, "registries_query_failed", err)
			return
		}
		var reg *storage.Registry
		for i := range regs {
			if regs[i].Name == registryName {
				reg = &regs[i]
				break
			}
		}
		if reg == nil {
			writeError(w, http.StatusNotFound, "registry_not_found", "registry "+registryName+" not found")
			return
		}
		if !reg.Enabled {
			writeError(w, http.StatusBadRequest, "registry_disabled", "registry "+registryName+" is disabled")
			return
		}
		ctx := clientConfigContextFromReq(opts, r, storage.Registry{
			ID:          reg.ID,
			Name:        reg.Name,
			UpstreamURL: reg.UpstreamURL,
			MirrorPath:  reg.MirrorPath,
			Enabled:     reg.Enabled,
			CreatedAt:   reg.CreatedAt,
		})

		now := nowUnix()
		resp := clientConfigResponse{
			Registry:    reg.Name,
			Hostname:    ctx.Hostname,
			Format:      format,
			CNCHBaseURL: ctx.BaseURL,
			GeneratedAt: now,
		}

		switch format {
		case "containerd-hosts":
			resp.Content = generateContainerdHostsTOML(ctx)
			resp.TargetPath = fmt.Sprintf("/etc/containerd/certs.d/%s/hosts.toml", ctx.Hostname)
			resp.RestartCmd = "systemctl restart containerd"
			resp.VerifyCmd = fmt.Sprintf("crictl pull %s/library/nginx:latest", ctx.Hostname)
		case "k3s-registries":
			resp.Content = generateK3sRegistriesYAML(ctx)
			resp.TargetPath = "/etc/rancher/k3s/registries.yaml"
			resp.RestartCmd = "systemctl restart k3s"
			resp.VerifyCmd = "crictl pull ghcr.io/jetstack/cert-manager-controller:v1.14.4"
		default:
			writeError(w, http.StatusBadRequest, "unsupported_format",
				"format must be containerd-hosts or k3s-registries")
			return
		}

		writeJSON(w, http.StatusOK, resp)
	}
}

// nowUnix 现在时间（unix 秒）。独立函数方便测试 mock。
func nowUnix() int64 {
	return timeNowUnix()
}

// ============================================================================
// §9.5.4 一键配置包导出（zip）
// ============================================================================

// bundleFile 是 zip 内的单个文件。
type bundleFile struct {
	path    string // zip 内路径，例 "docker/daemon.json"
	content []byte
}

// buildClientConfigBundle 构造配置包的所有文件（不写 zip）。
//
// 返回的 []bundleFile 顺序就是 zip 内顺序（unzip 工具按字母序排）。
// 每个文件都有自己的 header（容器化 + 注释 + 内容）。
//
// 设计：分开"build"和"write zip"两步，让 build 能在没注册表时也调，方便测试。
func buildClientConfigBundle(baseURL string, regs []storage.Registry) []bundleFile {
	now := timeNowUnix()
	files := []bundleFile{}

	// 1. docker/daemon.json
	files = append(files, bundleFile{
		path:    "docker/daemon.json",
		content: generateDockerDaemonJSON(baseURL, regs),
	})

	// 2. containerd/<hostname>/hosts.toml — 每个 enabled upstream 一个
	for _, reg := range regs {
		if !reg.Enabled {
			continue
		}
		host := registryHostnameFromUpstream(reg.Name)
		files = append(files, bundleFile{
			path:    fmt.Sprintf("containerd/%s/hosts.toml", host),
			content: []byte(generateContainerdHostsTOML(clientConfigContextFromURL(baseURL, reg, host))),
		})
	}

	// 3. k3s/registries.yaml — 包含所有 enabled upstream
	files = append(files, bundleFile{
		path:    "k3s/registries.yaml",
		content: generateK3sRegistriesYAMLMulti(baseURL, regs),
	})

	// 4. steamcmd/docker-compose.yml — DNS 加速 docker compose 模板
	files = append(files, bundleFile{
		path:    "steamcmd/docker-compose.yml",
		content: generateSteamCMDCompose(baseURL),
	})

	// 5. resource-accelerators/playwright.env
	files = append(files, bundleFile{
		path:    "resource-accelerators/playwright.env",
		content: generatePlaywrightEnv(baseURL),
	})

	// 6. resource-accelerators/puppeteer.env
	files = append(files, bundleFile{
		path:    "resource-accelerators/puppeteer.env",
		content: generatePuppeteerEnv(baseURL),
	})

	// 7. resource-accelerators/terraformrc
	files = append(files, bundleFile{
		path:    "resource-accelerators/terraformrc",
		content: generateTerraformRC(baseURL),
	})

	// 8. resource-accelerators/helm-repos.sh
	files = append(files, bundleFile{
		path:    "resource-accelerators/helm-repos.sh",
		content: generateHelmReposSh(baseURL),
	})

	// 9. verify.sh — 一键验证脚本
	files = append(files, bundleFile{
		path:    "verify.sh",
		content: generateVerifySh(baseURL, regs, now),
	})

	// 10. README.md — 用户引导
	files = append(files, bundleFile{
		path:    "README.md",
		content: generateBundleReadme(baseURL, regs, now),
	})

	return files
}

// clientConfigContextFromURL 用已知 baseURL 构造 ctx（不需要 request）。
func clientConfigContextFromURL(baseURL string, reg storage.Registry, hostname string) clientConfigContext {
	mirrorPath := reg.MirrorPath
	if mirrorPath == "" {
		mirrorPath = "/v2"
	}
	return clientConfigContext{
		BaseURL:     baseURL,
		Registry:    reg,
		RegistryURL: baseURL + mirrorPath,
		Hostname:    hostname,
	}
}

// generateDockerDaemonJSON 生成包含所有 enabled upstreams 的 daemon.json。
func generateDockerDaemonJSON(baseURL string, regs []storage.Registry) []byte {
	mirrors := []string{}
	insecure := []string{}
	for _, reg := range regs {
		if !reg.Enabled {
			continue
		}
		mirrorPath := reg.MirrorPath
		if mirrorPath == "" {
			mirrorPath = "/v2"
		}
		mirrors = append(mirrors, baseURL+mirrorPath)
		// 反代是 http → 客户端要 insecure-registries 加这个 host
		host := stripScheme(baseURL)
		if host != "" {
			insecure = append(insecure, host)
		}
	}
	// 去重
	mirrors = dedupStrings(mirrors)
	insecure = dedupStrings(insecure)

	body := fmt.Sprintf(`{
  "_comment": "Docker daemon config — generated by CNCacheHub",
  "_generated_at": %d,
  "_verify_cmd": "docker pull alpine:latest && docker info | grep -A5 'Registry Mirrors'",
  "registry-mirrors": [%s
  ],
  "insecure-registries": [%s
  ]
}
`, nowUnix(), joinQuoted(mirrors, "  "), joinQuoted(insecure, "  "))
	return []byte(body)
}

// generateK3sRegistriesYAMLMulti 生成 k3s registries.yaml 含所有 enabled upstreams。
func generateK3sRegistriesYAMLMulti(baseURL string, regs []storage.Registry) []byte {
	var b bytes.Buffer
	b.WriteString("# k3s / rke2 registries.yaml — generated by CNCacheHub\n")
	b.WriteString("# 目标路径：/etc/rancher/k3s/registries.yaml\n")
	b.WriteString("# 适用：k3s / rke2 / K8s containerd runtime\n")
	b.WriteString("#\n")
	b.WriteString("# 安装步骤：\n")
	b.WriteString("#   1. 写入到 /etc/rancher/k3s/registries.yaml\n")
	b.WriteString("#   2. systemctl restart k3s\n")
	b.WriteString("#   3. 验证：crictl pull alpine:latest\n")
	b.WriteString("#\n")
	b.WriteString("mirrors:\n")
	hasAny := false
	for _, reg := range regs {
		if !reg.Enabled {
			continue
		}
		host := registryHostnameFromUpstream(reg.Name)
		fmt.Fprintf(&b, "  %q:\n", host)
		fmt.Fprintf(&b, "    endpoint:\n")
		fmt.Fprintf(&b, "      - %q\n", baseURL)
		hasAny = true
	}
	if !hasAny {
		b.WriteString("  # (no enabled upstreams — 在 Web UI 启用至少一个 registry)\n")
	}
	return b.Bytes()
}

// generateSteamCMDCompose 生成 SteamCMD docker-compose 模板。
//
// 用法：用户拷贝后 docker compose up -d steamcmd，然后在容器内跑 steamcmd。
// 通过 dns 字段指向 CNCacheHub 内置 DNS（5353）让 Steam 走 CNCH 加速。
func generateSteamCMDCompose(baseURL string) []byte {
	cnchIP := "host.docker.internal" // Docker Desktop 风格；Linux 下需要 extra_hosts
	return []byte(fmt.Sprintf(`# SteamCMD Docker Compose — generated by CNCacheHub
# 用法：
#   1. cd steamcmd/
#   2. docker compose up -d
#   3. docker compose exec steamcmd bash -c "steamcmd +login anonymous +force_install_dir /home/steam/csgo +app_update 740 validate +quit"
#
# 加速原理：让容器 DNS 走 CNCacheHub 内置的 mini DNS（UDP 5353），
# 把 *.steamcontent.com / *.steamstatic.com 等 Steam 域名劫持到 CNCH。
# 注意：CNCacheHub DNS server 监听 0.0.0.0:5353（非标准 53 端口，免 root）。

services:
  steamcmd:
    image: cm2network/steamcmd:root
    container_name: cnch-steamcmd
    restart: unless-stopped
    # 把 CNCH 监听地址告诉容器：Linux 上需在 host 上跑 CNCH 监听 5353
    extra_hosts:
      - "cncachehub:%s"
    # 让容器走 CNCH 的 DNS
    dns:
      - %s
    environment:
      # CNCH base URL（容器内可通过 extra_hosts 解析；可改成实际 IP）
      CNCH_BASE_URL: "%s"
    volumes:
      - ./data:/home/steam/data
    tty: true
    stdin_open: true
`, cnchIP, cnchIP, baseURL))
}

// generatePlaywrightEnv 输出 PLAYWRIGHT_DOWNLOAD_HOST 配置。
//
// 注意：playwright 的 host 是浏览器二进制下载 CDN，rule name 是 "playwright"。
// 客户端 URL: <cnch>/r/<rule>/<path>。
func generatePlaywrightEnv(baseURL string) []byte {
	return []byte(fmt.Sprintf(`# Playwright 配置 — generated by CNCacheHub
# 用法：source playwright.env && npx playwright install
#
# 原理：让 Playwright 浏览器二进制从 CNCH 拉（/r/playwright/<path>），
# 走 CNCH 的白名单 + 缓存，比默认 CDN 更快更稳。

export PLAYWRIGHT_DOWNLOAD_HOST=%s/r/playwright
`, baseURL))
}

// generatePuppeteerEnv 输出 PUPPETEER_DOWNLOAD_BASE_URL 配置。
//
// 默认 puppeteer 走 storage.googleapis.com；用 CNCH 的 chromium rule 代理。
// 客户端 URL: <cnch>/r/<rule>/<path>。
func generatePuppeteerEnv(baseURL string) []byte {
	return []byte(fmt.Sprintf(`# Puppeteer 配置 — generated by CNCacheHub
# 用法：source puppeteer.env && node your-script.js
#
# 原理：Puppeteer 浏览器二进制从 CNCH 拉（/r/puppeteer/<path>），
# 走 CNCH 的白名单 + 缓存。

export PUPPETEER_DOWNLOAD_BASE_URL=%s/r/puppeteer
`, baseURL))
}

// generateTerraformRC 输出 .terraformrc 配置（Terraform provider mirror）。
func generateTerraformRC(baseURL string) []byte {
	return []byte(fmt.Sprintf(`# Terraform CLI 配置 — generated by CNCacheHub
# 用法：cp terraformrc ~/.terraformrc
#
# 原理：让 terraform 从 CNCH 拉 provider（/r/terraform/<path>），
# 走 CNCH 的白名单 + 缓存。CNCH 会校验 checksum 不跳过。

provider_installation {
  network_mirror {
    url = "%s/r/terraform"
  }
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
}
`, baseURL))
}

// generateHelmReposSh 输出 helm repo add 脚本。
func generateHelmReposSh(baseURL string) []byte {
	return []byte(fmt.Sprintf(`#!/usr/bin/env bash
# Helm repo 加速 — generated by CNCacheHub
# 用法：bash helm-repos.sh
#
# 原理：用 CNCH 代理 helm 仓库索引 + chart 下载（/r/helm/<path>）。
# 注意：helm repo add 走 index.yaml；CNCH 代理后端 chartmuseum/repo。

set -euo pipefail
CNCH_BASE="%s/r/helm"

# 常用 chart 仓库示例（按需取消注释 / 增删）
# helm repo add bitnami   "$CNCH_BASE/charts.bitnami.com/bitnami"   --force-update
# helm repo add prometheus-community "$CNCH_BASE/prometheus-community.github.io" --force-update
# helm repo add jetstack  "$CNCH_BASE/charts.jetstack.io"           --force-update

helm repo update
echo "Done. Run 'helm search repo <name>' to verify."
`, baseURL))
}

// generateVerifySh 一键验证脚本。
func generateVerifySh(baseURL string, regs []storage.Registry, now int64) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# CNCacheHub 一键验证脚本 — generated at %d\n", now)
	fmt.Fprintf(&b, "# 用法：bash verify.sh\n")
	fmt.Fprintf(&b, "set -uo pipefail\n\n")
	fmt.Fprintf(&b, "CNCH_BASE=%q\n", baseURL)
	fmt.Fprintf(&b, "PASS=0\nFAIL=0\n\n")
	b.WriteString(`note() { printf '\033[36m%s\033[0m\n' "$*"; }
`)
	b.WriteString(`ok()   { printf '\033[32m✓ %s\033[0m\n' "$*"; PASS=$((PASS+1)); }
`)
	b.WriteString(`bad()  { printf '\033[31m✗ %s\033[0m\n' "$*"; FAIL=$((FAIL+1)); }
`)

	// 1. /api/healthz
	b.WriteString(`
note "[1/4] Checking CNCacheHub reachable..."
if code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "$CNCH_BASE/api/healthz" 2>/dev/null); then
  if [ "$code" = "200" ]; then
    ok "GET /api/healthz = 200"
  else
    bad "GET /api/healthz = $code"
  fi
else
  bad "curl /api/healthz failed (check network/port)"
fi
`)

	// 2. /v2/
	b.WriteString(`
note "[2/4] Checking registry endpoint..."
if code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 5 "$CNCH_BASE/v2/" 2>/dev/null); then
  if [ "$code" = "200" ]; then
    ok "GET /v2/ = 200 (Docker registry v2 protocol)"
  else
    bad "GET /v2/ = $code"
  fi
else
  bad "curl /v2/ failed"
fi
`)

	// 3. docker pull (if docker exists)
	b.WriteString(`
note "[3/4] Trying docker pull alpine:latest (if docker available)..."
if command -v docker >/dev/null 2>&1; then
  if docker pull alpine:latest >/dev/null 2>&1; then
    ok "docker pull alpine:latest succeeded"
  else
    bad "docker pull failed (check daemon.json + docker daemon restart)"
  fi
else
  note "docker not installed, skipping"
fi
`)

	// 4. resource accelerator smoke test
	b.WriteString(`
note "[4/4] Resource accelerator smoke test (GitHub raw)..."
if code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 8 "$CNCH_BASE/r/github-release/golang/go/master/CONTRIBUTING.md" 2>/dev/null); then
  if [ "$code" = "200" ]; then
    ok "GET /r/github-release/.../CONTRIBUTING.md = 200"
  else
    bad "GET /r/github-release returned $code (rule disabled?)"
  fi
else
  bad "curl /r/github-release failed"
fi

echo
printf 'Result: \033[32m%d pass\033[0m, \033[31m%d fail\033[0m\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
`)
	return b.Bytes()
}

// generateBundleReadme 生成 README.md。
func generateBundleReadme(baseURL string, regs []storage.Registry, now int64) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# CNCacheHub Client Config Bundle\n\n")
	fmt.Fprintf(&b, "_Generated at: %s_\n\n", time.Unix(now, 0).UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "CNCacheHub base URL: `%s`\n\n", baseURL)
	fmt.Fprintf(&b, "## 文件清单\n\n")
	fmt.Fprintf(&b, "| 文件 | 用途 | 目标机器 |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| `docker/daemon.json` | Docker Engine 镜像加速 | 装 docker 的机器（粘贴到 `/etc/docker/daemon.json`） |\n")
	fmt.Fprintf(&b, "| `containerd/<host>/hosts.toml` | containerd/nerdctl 加速 | 装 containerd 的机器（粘贴到 `/etc/containerd/certs.d/<host>/hosts.toml`） |\n")
	fmt.Fprintf(&b, "| `k3s/registries.yaml` | k3s / rke2 加速 | k3s 节点（粘贴到 `/etc/rancher/k3s/registries.yaml`） |\n")
	fmt.Fprintf(&b, "| `steamcmd/docker-compose.yml` | SteamCMD Docker 启动器 + DNS 加速 | 任意装 docker 的机器 |\n")
	fmt.Fprintf(&b, "| `resource-accelerators/playwright.env` | Playwright 浏览器下载加速 | CI / 测试机（`source` 后 `npx playwright install`） |\n")
	fmt.Fprintf(&b, "| `resource-accelerators/puppeteer.env` | Puppeteer 浏览器下载加速 | 同上 |\n")
	fmt.Fprintf(&b, "| `resource-accelerators/terraformrc` | Terraform provider 加速 | `cp terraformrc ~/.terraformrc` |\n")
	fmt.Fprintf(&b, "| `resource-accelerators/helm-repos.sh` | Helm 仓库加速脚本 | `bash helm-repos.sh` |\n")
	fmt.Fprintf(&b, "| `verify.sh` | 一键验证（健康检查 + docker pull + 资源加速） | 任意机器（`bash verify.sh`） |\n")
	fmt.Fprintf(&b, "| `README.md` | 本文件 | - |\n\n")

	fmt.Fprintf(&b, "## 已启用的 Registry\n\n")
	hasAny := false
	for _, reg := range regs {
		if !reg.Enabled {
			continue
		}
		host := registryHostnameFromUpstream(reg.Name)
		fmt.Fprintf(&b, "- `%s` (→ `%s`)\n", reg.Name, host)
		hasAny = true
	}
	if !hasAny {
		fmt.Fprintf(&b, "_无。访问 CNCacheHub Web UI 启用至少一个 registry upstreams。_\n")
	}
	fmt.Fprintf(&b, "\n")

	fmt.Fprintf(&b, "## 快速验证\n\n")
	fmt.Fprintf(&b, "```bash\nbash verify.sh\n```\n\n")
	fmt.Fprintf(&b, "期望：4/4 通过（如果 docker 没装会跳过 1 项）。\n\n")

	fmt.Fprintf(&b, "## 接入步骤（Docker Engine 例子）\n\n")
	fmt.Fprintf(&b, "1. **拷贝 daemon.json**：\n")
	fmt.Fprintf(&b, "   ```bash\n")
	fmt.Fprintf(&b, "   sudo mkdir -p /etc/docker\n")
	fmt.Fprintf(&b, "   sudo cp docker/daemon.json /etc/docker/daemon.json\n")
	fmt.Fprintf(&b, "   ```\n")
	fmt.Fprintf(&b, "2. **重启 docker**：\n")
	fmt.Fprintf(&b, "   ```bash\n")
	fmt.Fprintf(&b, "   sudo systemctl restart docker\n")
	fmt.Fprintf(&b, "   ```\n")
	fmt.Fprintf(&b, "3. **验证**：\n")
	fmt.Fprintf(&b, "   ```bash\n")
	fmt.Fprintf(&b, "   docker info | grep -A5 'Registry Mirrors'\n")
	fmt.Fprintf(&b, "   docker pull alpine:latest\n")
	fmt.Fprintf(&b, "   ```\n\n")

	fmt.Fprintf(&b, "## 回滚\n\n")
	fmt.Fprintf(&b, "所有文件都覆盖本地配置，建议先备份：\n")
	fmt.Fprintf(&b, "```bash\n")
	fmt.Fprintf(&b, "sudo cp /etc/docker/daemon.json /etc/docker/daemon.json.bak\n")
	fmt.Fprintf(&b, "sudo cp /etc/rancher/k3s/registries.yaml /etc/rancher/k3s/registries.yaml.bak\n")
	fmt.Fprintf(&b, "```\n")
	return b.Bytes()
}

// generateClientConfigBundleHandler POST /api/client-config/bundle
//
// 流式返回 .zip — 公开端点（跟 /api/client-config 一样）。
func generateClientConfigBundleHandler(opts Options) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if opts.ListRegistries == nil {
			writeError(w, http.StatusServiceUnavailable, "client_config_unavailable", "registries not configured")
			return
		}
		regs, err := opts.ListRegistries(r.Context())
		if err != nil {
			writeInternalErr(w, r, "registries_query_failed", err)
			return
		}
		base := clientBaseURL(opts, r)
		files := buildClientConfigBundle(base, regs)

		// 写 zip header
		filename := fmt.Sprintf("cncachehub-client-config-%s.zip", time.Now().UTC().Format("20060102-150405"))
		w.Header().Set("Content-Type", "application/zip")
		w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
		w.WriteHeader(http.StatusOK)

		// 构造 zip（写到内存 — bundle 10 个文件很小 < 10KB）
		var buf bytes.Buffer
		zw := zip.NewWriter(&buf)
		for _, f := range files {
			h := &zip.FileHeader{
				Name:     f.path,
				Modified: time.Unix(timeNowUnix(), 0),
				Method:   zip.Deflate,
			}
			fw, err := zw.CreateHeader(h)
			if err != nil {
				continue // best-effort
			}
			_, _ = fw.Write(f.content)
		}
		_ = zw.Close()

		// 流式写
		_, _ = w.Write(buf.Bytes())
	}
}

// === helpers ===

func dedupStrings(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}

func joinQuoted(items []string, indent string) string {
	if len(items) == 0 {
		return ""
	}
	var b strings.Builder
	for i, s := range items {
		if i > 0 {
			b.WriteString(",\n")
		}
		b.WriteString(indent)
		fmt.Fprintf(&b, "%q", s)
	}
	return b.String()
}

func stripScheme(url string) string {
	if i := strings.Index(url, "://"); i >= 0 {
		return url[i+3:]
	}
	return url
}
